### PR TITLE
Fixed Reference Bug.

### PR DESCRIPTION
**Pull request by st0le**
cs-gamestate is broken due to this.

Please update the npm packages aswell.

### CODE REVIEW

**Comment by schroffl** [comment]
Thank you very much :)

**Comment by schroffl** [comment]
Published in [v0.3.2](https://www.npmjs.com/package/object-differ/v/0.3.2)

**Comment by st0le** [comment]
Please publish cs-gamestate with 0.3.2.

**Comment by schroffl** [comment]
Freshly installing `cs-gamestate` should automatically pull in `0.3.2`, because of [this dependency version constraint](https://github.com/schroffl/cs-gamestate/blob/master/package.json#L26).
I'm not sure though – if it doesn't work just tell me and I will take care of it tomorrow.

**Comment by st0le** [comment]
My apologies, you are right. I don't know how that works. New to nodejs. Thanks again.

**Pull request merged**
